language: ruby
rvm:
  - 1.9.3
  - 2.3.0
script: 
  - "rake lint"
  - "rake spec"
  - "rake validate"
branches:
  only:
    - master
env:
  - PUPPET_GEM_VERSION="~> 4.4.0"
  - PUPPET_GEM_VERSION="~> 4.2.0"
  - PUPPET_GEM_VERSION="~> 4.0.0"
notifications:
  email: false
gemfile: .gemfile
