language: ruby
rvm:
  - 1.8.7
  - 2.3.0
script: "rake spec"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=4.2.0
  - PUPPET_VERSION=3.8.0
  - PUPPET_VERSION=2.7.17
  - PUPPET_VERSION=2.7.13
  - PUPPET_VERSION=2.7.9
  - PUPPET_VERSION=2.6.9
notifications:
  email: false
gemfile: .gemfile
